export const HOME ="/";
export const ABOUT="/about";
export const SKILLS="/skills";
export const BLOGS="/blogs";
export const CONTACT ="/contact";
export const RESUME ="/resume";
export const  LOGIN ="/login";
export const CREATEBLOG='/createblog';
export const FullBlog='/blogs/:id';
export const COMMENTS='/comments'